// web/src/components/BlockOutliner.tsx
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import Link from "next/link";

import { parseBlocks, extractWikiLinks } from "@/lib/block-parser";
import type { ParsedBlock } from "@/lib/types/ParsedBlock";
import { BlockEditor } from "./BlockEditor";

export function BlockOutliner({
  noteId,
  body,
  frontmatter,
  onContentChange,
}: {
  noteId: string;
  body: string;
  frontmatter: string;
  onContentChange?: (fullContent: string) => void;
}) {
  const initialBlocks = useMemo(() => parseBlocks(noteId, body), [noteId, body]);
  const [blocks, setBlocks] = useState(initialBlocks);
  const [focusedIndex, setFocusedIndex] = useState<number | null>(null);
  const blocksRef = useRef(blocks);

  useEffect(() => {
    blocksRef.current = blocks;
  }, [blocks]);

  const saveBlocks = useCallback(
    (updated: ParsedBlock[]) => {
      const bodyLines = updated
        .map((b) => {
          const indent = "  ".repeat(b.indent_level);
          const contIndent = indent + "  "; // continuation lines get one extra level
          const lines = b.raw_text.split("\n");
          const first = `${indent}- ${lines[0]}`;
          const rest = lines.slice(1).map((l) => `${contIndent}${l}`);
          return [first, ...rest].join("\n");
        })
        .join("\n");
      onContentChange?.(`${frontmatter}${bodyLines}\n`);
    },
    [frontmatter, onContentChange],
  );

  const handleBlockChange = useCallback(
    (blockId: string, newRawText: string) => {
      setBlocks((prev) => {
        const updated = prev.map((b) =>
          b.id === blockId ? { ...b, raw_text: newRawText, text: newRawText.split("\n")[0]?.replace(/#([A-Za-z0-9_/-]+)/g, "").trim() ?? "" } : b,
        );
        blocksRef.current = updated;
        saveBlocks(updated);
        return updated;
      });
    },
    [saveBlocks],
  );

  const handleNavigate = useCallback(
    (direction: "up" | "down") => {
      setFocusedIndex((current) => {
        if (current === null) return null;
        const next =
          direction === "up"
            ? Math.max(0, current - 1)
            : Math.min(blocksRef.current.length - 1, current + 1);
        return next;
      });
    },
    [],
  );

  const handleEscape = useCallback(() => {
    setFocusedIndex(null);
  }, []);

  const handleEnter = useCallback(
    (atIndex: number) => {
      setBlocks((prev) => {
        const current = prev[atIndex];
        if (!current) return prev;
        const newBlock: ParsedBlock = {
          id: `${noteId}:new-${Date.now()}`,
          text: "",
          raw_text: "",
          tags: [],
          properties: {},
          indent_level: current.indent_level,
          note_id: noteId,
        };
        const updated = [...prev.slice(0, atIndex + 1), newBlock, ...prev.slice(atIndex + 1)];
        blocksRef.current = updated;
        saveBlocks(updated);
        return updated;
      });
      setFocusedIndex(atIndex + 1);
    },
    [noteId, saveBlocks],
  );

  const handleIndent = useCallback(
    (atIndex: number, direction: "indent" | "outdent") => {
      setBlocks((prev) => {
        const block = prev[atIndex];
        if (!block) return prev;
        const newLevel =
          direction === "indent"
            ? block.indent_level + 1
            : Math.max(0, block.indent_level - 1);
        if (newLevel === block.indent_level) return prev;
        const updated = prev.map((b, i) =>
          i === atIndex ? { ...b, indent_level: newLevel } : b,
        );
        blocksRef.current = updated;
        saveBlocks(updated);
        return updated;
      });
    },
    [saveBlocks],
  );

  const handleBackspace = useCallback(
    (atIndex: number) => {
      setBlocks((prev) => {
        const block = prev[atIndex];
        if (!block || block.raw_text !== "") return prev; // Only delete empty blocks
        if (prev.length <= 1) return prev; // Don't delete the last block
        const updated = prev.filter((_, i) => i !== atIndex);
        blocksRef.current = updated;
        saveBlocks(updated);
        return updated;
      });
      setFocusedIndex((current) => {
        if (current === null || current === 0) return current;
        return current - 1;
      });
    },
    [saveBlocks],
  );

  // Keyboard nav when no block is focused
  const containerRef = useRef<HTMLDivElement>(null);
  useEffect(() => {
    const el = containerRef.current;
    if (!el || focusedIndex !== null) return;

    const handler = (e: KeyboardEvent) => {
      if (e.key === "ArrowDown" || e.key === "j") {
        e.preventDefault();
        setFocusedIndex(0);
      }
    };
    el.addEventListener("keydown", handler);
    return () => el.removeEventListener("keydown", handler);
  }, [focusedIndex]);

  if (blocks.length === 0) {
    return (
      <div className="text-sm text-muted-foreground italic">
        No blocks. Start typing with &quot;- &quot; to create one.
      </div>
    );
  }

  return (
    <div ref={containerRef} className="space-y-0.5" tabIndex={-1}>
      {blocks.map((block, index) => (
        <BlockItem
          key={block.id}
          block={block}
          isFocused={focusedIndex === index}
          onFocus={() => setFocusedIndex(index)}
          onBlur={() => {
            setFocusedIndex((current) =>
              current === index ? null : current,
            );
          }}
          onNavigate={handleNavigate}
          onEscape={handleEscape}
          onEnter={() => handleEnter(index)}
          onIndent={(dir) => handleIndent(index, dir)}
          onBackspaceEmpty={() => handleBackspace(index)}
          onChange={handleBlockChange}
        />
      ))}
    </div>
  );
}

function BlockItem({
  block,
  isFocused,
  onFocus,
  onBlur,
  onNavigate,
  onEscape,
  onEnter,
  onIndent,
  onBackspaceEmpty,
  onChange,
}: {
  block: ParsedBlock;
  isFocused: boolean;
  onFocus: () => void;
  onBlur: () => void;
  onNavigate: (direction: "up" | "down") => void;
  onEscape: () => void;
  onEnter: () => void;
  onIndent: (direction: "indent" | "outdent") => void;
  onBackspaceEmpty: () => void;
  onChange: (blockId: string, newRawText: string) => void;
}) {
  const indent = block.indent_level * 24;

  return (
    <div
      className={`group flex items-start gap-1.5 rounded-sm transition-colors ${
        isFocused ? "bg-accent/20" : "hover:bg-accent/30"
      }`}
      style={{ paddingLeft: `${indent}px` }}
    >
      <span className="mt-[7px] h-1.5 w-1.5 shrink-0 rounded-full bg-muted-foreground/50" />
      <div className="flex-1 min-w-0 py-0.5">
        {isFocused ? (
          <BlockEditor
            initialText={block.raw_text}
            onBlur={onBlur}
            onChange={(text: string) => onChange(block.id, text)}
            onNavigate={onNavigate}
            onEscape={onEscape}
            onEnter={onEnter}
            onIndent={onIndent}
            onBackspaceEmpty={onBackspaceEmpty}
          />
        ) : (
          <div
            className="text-sm leading-relaxed cursor-text min-h-[24px]"
            onClick={onFocus}
          >
            <BlockDisplayText block={block} />
            {block.tags.length > 0 && (
              <span className="ml-2 inline-flex gap-1">
                {block.tags.map((tag) => (
                  <Link
                    key={tag}
                    href={`/p/${encodeURIComponent(tag.toLowerCase())}`}
                    className="text-xs px-1.5 py-0.5 rounded bg-accent text-accent-foreground hover:bg-accent/80"
                    onClick={(e) => e.stopPropagation()}
                  >
                    #{tag}
                  </Link>
                ))}
              </span>
            )}
            {Object.keys(block.properties).length > 0 && (
              <div className="mt-0.5 space-y-0">
                {Object.entries(block.properties).map(([key, value]) => (
                  <div key={key} className="text-xs text-muted-foreground">
                    <span className="text-muted-foreground/70">{key}::</span>{" "}
                    <PropertyValue value={value} />
                  </div>
                ))}
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  );
}

function BlockDisplayText({ block }: { block: ParsedBlock }) {
  const text = block.text;
  const links = extractWikiLinks(text);

  if (links.length === 0) {
    return <span>{text}</span>;
  }

  const parts: React.ReactNode[] = [];
  let lastEnd = 0;
  for (const link of links) {
    if (link.start > lastEnd) {
      parts.push(<span key={`t${lastEnd}`}>{text.slice(lastEnd, link.start)}</span>);
    }
    parts.push(
      <Link
        key={`l${link.start}`}
        href={`/p/${encodeURIComponent(link.target.toLowerCase())}`}
        className="text-primary underline underline-offset-2 decoration-primary/40 hover:decoration-primary"
        onClick={(e) => e.stopPropagation()}
      >
        {link.display}
      </Link>,
    );
    lastEnd = link.end;
  }
  if (lastEnd < text.length) {
    parts.push(<span key={`t${lastEnd}`}>{text.slice(lastEnd)}</span>);
  }

  return <>{parts}</>;
}

function PropertyValue({ value }: { value: string }) {
  const links = extractWikiLinks(value);
  if (links.length === 0) return <span>{value}</span>;

  const parts: React.ReactNode[] = [];
  let lastEnd = 0;
  for (const link of links) {
    if (link.start > lastEnd) {
      parts.push(<span key={`t${lastEnd}`}>{value.slice(lastEnd, link.start)}</span>);
    }
    parts.push(
      <Link
        key={`l${link.start}`}
        href={`/p/${encodeURIComponent(link.target.toLowerCase())}`}
        className="text-primary underline underline-offset-2 decoration-primary/40 hover:decoration-primary"
      >
        {link.display}
      </Link>,
    );
    lastEnd = link.end;
  }
  if (lastEnd < value.length) {
    parts.push(<span key={`t${lastEnd}`}>{value.slice(lastEnd)}</span>);
  }
  return <>{parts}</>;
}

// .docs/designs/v9-columns/web/src/lib/components/BlockOutliner.svelte
<script lang="ts">
  import { createQuery } from "@tanstack/svelte-query";
  import { parseBlocks } from "$lib/block-parser";
  import { api } from "$lib/api-client";
  import type { ParsedBlock } from "$lib/types/ParsedBlock";
  import type { Note } from "$lib/types/Note";
  import BlockEditor from "./BlockEditor.svelte";

  let {
    noteId,
    body,
    frontmatter,
    onContentChange,
    onleader: onLeader,
  }: {
    noteId: string;
    body: string;
    frontmatter: string;
    onContentChange?: (fullContent: string) => void;
    onleader?: () => void;
  } = $props();

  // Fetch notes list for autocomplete
  const notesForAutocomplete = createQuery(() => ({
    queryKey: ["notes", { limit: 200 }] as const,
    queryFn: () => api.listNotes({ limit: 200 }),
  }));
  const notesList = $derived(
    ((notesForAutocomplete.data ?? []) as Note[]).map((n) => ({
      id: n.id,
      title: n.title,
      tags: n.metadata.tags,
    })),
  );

  let blocks = $state<ParsedBlock[]>(parseBlocks(noteId, body));
  let focusedIndex = $state<number | null>(null);
  let lastBodyFromServer = $state(body);

  $effect(() => {
    if (body !== lastBodyFromServer) {
      lastBodyFromServer = body;
      if (focusedIndex === null) {
        blocks = parseBlocks(noteId, body);
      }
    }
  });

  function saveBlocks(updated: ParsedBlock[]) {
    const bodyLines = updated
      .map((b) => {
        const indent = "  ".repeat(b.indent_level);
        const lines = b.raw_text.split("\n");
        const first = `${indent}- ${lines[0]}`;
        const rest = lines.slice(1).map((l: string) => `${indent}  ${l}`);
        return [first, ...rest].join("\n");
      })
      .join("\n");
    onContentChange?.(`${frontmatter}${bodyLines}\n`);
  }

  function handleBlockChange(blockId: string, newRawText: string) {
    blocks = blocks.map((b) =>
      b.id === blockId
        ? { ...b, raw_text: newRawText, text: (newRawText.split("\n")[0] ?? "").replace(/#([A-Za-z0-9_/-]+)/g, "").trim() }
        : b,
    );
    saveBlocks(blocks);
  }

  function handleNavigate(direction: "up" | "down") {
    if (focusedIndex === null) return;
    const next = direction === "up"
      ? Math.max(0, focusedIndex - 1)
      : Math.min(blocks.length - 1, focusedIndex + 1);
    focusedIndex = next;
  }

  function handleEnter(atIndex: number) {
    const current = blocks[atIndex];
    if (!current) return;
    const newBlock: ParsedBlock = {
      id: `${noteId}:new-${Date.now()}`,
      text: "",
      raw_text: "",
      tags: [],
      properties: {},
      indent_level: current.indent_level,
      note_id: noteId,
    };
    blocks = [...blocks.slice(0, atIndex + 1), newBlock, ...blocks.slice(atIndex + 1)];
    saveBlocks(blocks);
    focusedIndex = atIndex + 1;
  }

  function handleIndent(atIndex: number, direction: "indent" | "outdent") {
    const block = blocks[atIndex];
    if (!block) return;
    const newLevel = direction === "indent" ? block.indent_level + 1 : Math.max(0, block.indent_level - 1);
    if (newLevel === block.indent_level) return;
    blocks = blocks.map((b, i) => (i === atIndex ? { ...b, indent_level: newLevel } : b));
    saveBlocks(blocks);
  }

  function handleBackspace(atIndex: number) {
    const block = blocks[atIndex];
    if (!block || block.raw_text !== "" || blocks.length <= 1) return;
    blocks = blocks.filter((_, i) => i !== atIndex);
    saveBlocks(blocks);
    if (focusedIndex !== null && focusedIndex > 0) focusedIndex = focusedIndex - 1;
  }

  // Block clipboard for yy/p
  let blockClipboard = $state<ParsedBlock | null>(null);

  function handleDeleteBlock(atIndex: number) {
    if (blocks.length <= 1) return;
    const prev = Math.max(0, atIndex - 1);
    blocks = blocks.filter((_, i) => i !== atIndex);
    saveBlocks(blocks);
    focusedIndex = Math.min(prev, blocks.length - 1);
  }

  function handleYankBlock(atIndex: number) {
    const block = blocks[atIndex];
    if (block) blockClipboard = { ...block };
  }

  function handlePasteBlock(atIndex: number) {
    if (!blockClipboard) return;
    const pasted: ParsedBlock = {
      ...blockClipboard,
      id: `${noteId}:paste-${Date.now()}`,
    };
    blocks = [...blocks.slice(0, atIndex + 1), pasted, ...blocks.slice(atIndex + 1)];
    saveBlocks(blocks);
    focusedIndex = atIndex + 1;
  }

  function handleNewBlockAbove(atIndex: number) {
    const current = blocks[atIndex];
    if (!current) return;
    const newBlock: ParsedBlock = {
      id: `${noteId}:new-${Date.now()}`,
      text: "",
      raw_text: "",
      tags: [],
      properties: {},
      indent_level: current.indent_level,
      note_id: noteId,
    };
    blocks = [...blocks.slice(0, atIndex), newBlock, ...blocks.slice(atIndex)];
    saveBlocks(blocks);
    focusedIndex = atIndex;
  }
</script>

{#if blocks.length === 0}
  <!-- svelte-ignore a11y_click_events_have_key_events -->
  <!-- svelte-ignore a11y_no_static_element_interactions -->
  <div
    class="text-sm text-muted-foreground cursor-text py-2 hover:bg-accent/20 rounded px-2"
    onclick={() => {
      const newBlock = {
        id: `${noteId}:new-${Date.now()}`,
        text: "",
        raw_text: "",
        tags: [],
        properties: {},
        indent_level: 0,
        note_id: noteId,
      };
      blocks = [newBlock];
      focusedIndex = 0;
    }}
  >
    Click to start writing…
  </div>
{:else}
  <div class="space-y-1">
    {#each blocks as block, index (block.id)}
      <div
        class="group flex items-start transition-all relative"
        style="padding-left: {block.indent_level * 24}px; {block.indent_level === 0 ? `background: var(--block-bg); border-radius: var(--block-radius, 8px); box-shadow: ${focusedIndex === index ? 'var(--focus-glow)' : 'var(--block-shadow)'}; border: 1px solid var(--block-border);` : ''}"
      >
        <!-- Threading lines -->
        {#if block.indent_level > 0}
          {#each { length: block.indent_level } as _, lvl}
            <span
              class="absolute top-0 bottom-0 w-px"
              style="left: {lvl * 24 + 10}px; background: var(--thread-border);"
            ></span>
          {/each}
        {/if}

        <!-- Bullet -->
        <div class="shrink-0 pt-[14px] pl-2 pr-1">
          <span
            class="block w-[6px] h-[6px] rounded-full transition-colors {focusedIndex === index ? 'bg-primary' : 'bg-muted-foreground/40'}"
          ></span>
        </div>

        <!-- Content -->
        <div class="flex-1 min-w-0 py-2 pr-3">
          <BlockEditor
            initialText={block.raw_text}
            onblur={() => { if (focusedIndex === index) focusedIndex = null; }}
            onfocus={() => { focusedIndex = index; }}
            onchange={(text) => handleBlockChange(block.id, text)}
            onnavigate={handleNavigate}
            onescape={() => { focusedIndex = null; }}
            onenter={() => handleEnter(index)}
            onindent={(dir) => handleIndent(index, dir)}
            onbackspaceempty={() => handleBackspace(index)}
            startininsert={focusedIndex === index && block.raw_text === ""}
            onleader={onLeader}
            ondeleteblock={() => handleDeleteBlock(index)}
            onyankblock={() => handleYankBlock(index)}
            onpasteblock={() => handlePasteBlock(index)}
            onnewblockbelow={() => handleEnter(index)}
            onnewblockabove={() => handleNewBlockAbove(index)}
            focused={focusedIndex === index}
            noteslist={notesList}
          />
        </div>
      </div>
    {/each}
  </div>
{/if}
